KS-1-4 the solution to lesson 1 task 4
DusikINDusik/KotlinSprint pull request #5
Opened 2024-12-13 15:08 UTC by DusikINDusik

выполненное задание к уроку 1 задаче 4

2024-12-14 17:51 UTC, ievetrovdev requested changes

2024-12-14 17:51 UTC, ievetrovdev commented on src/main/kotlin/Lesson1/lesson1-task4.kt
> +    val seconds: Int = 6480
Для этого значения можно применить тип, который занимает еще меньше места в памяти)

2024-12-14 17:51 UTC, ievetrovdev commented on src/main/kotlin/Lesson1/lesson1-task4.kt
> +fun main (){
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-12-14 18:25 UTC, DusikINDusik reviewed
changed

2024-12-15 18:32 UTC, ievetrovdev approved these changes

2024-12-17 15:15 UTC, merged