KS-2-2 the solution to lesson 2 task 2
DusikINDusik/KotlinSprint pull request #7
Opened 2024-12-14 14:16 UTC by DusikINDusik

выполненное задание к уроку 2 задаче 2

2024-12-14 18:04 UTC, ievetrovdev requested changes
Для красоты лучше разбить код на блоки, разделяемые пустыми строками. Примерно так:
 - объявление переменных
 - вычисления
 - вывод результата

2024-12-14 18:04 UTC, ievetrovdev commented on src/main/kotlin/Lesson2/lesson2-task2.kt
> +
Старайся избегать лишних двойных пустых строк)
Это размывает внимание, нарушает единый стиль)

2024-12-14 18:04 UTC, ievetrovdev commented on src/main/kotlin/Lesson2/lesson2-task2.kt
> +    var ExpensEmployeIntern = salaryExpensesIntern + salaryExpensesEmployees
Предлагаю использовать стиль [lowerCamelCase](https://ru.wikipedia.org/wiki/CamelCase)

2024-12-14 18:37 UTC, DusikINDusik reviewed
changed

2024-12-15 18:34 UTC, ievetrovdev approved these changes

2024-12-17 15:15 UTC, merged